name: Build TWRP for Infinix Smart 5 (X657B)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev \
            gcc-multilib g++-multilib libc6-dev-i386 libncurses5-dev x11proto-core-dev \
            libx11-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig

      - name: Init repo
        run: |
          mkdir twrp && cd twrp
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-12.1
          repo sync -j$(nproc) --force-sync

      - name: Copy device tree
        run: |
          mkdir -p twrp/device/infinix
          cp -r device/infinix/x657b twrp/device/infinix/x657b

      - name: Lunch & Build
        run: |
          cd twrp
          source build/envsetup.sh
          lunch omni_x657b-eng
          mka recoveryimage

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: twrp-recovery-x657b
          path: twrp/out/target/product/x657b/recovery.img
