name: Build TWRP for Infinix Smart 5 (X657B)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc bison build-essential ccache curl flex g++-multilib gcc-multilib \
            git gnupg gperf imagemagick lib32ncurses5-dev lib32z1-dev \
            liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev \
            libxml2 libxml2-utils lzop pngcrush rsync schedtool \
            squashfs-tools xsltproc zip zlib1g-dev python3 openjdk-11-jdk

      - name: Install repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Sync TWRP source
        run: |
          mkdir twrp && cd twrp
          repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-12.1
          repo sync -j$(nproc --all) --force-sync

      - name: Clone device tree
        run: |
          cd twrp
          git clone https://github.com/suryonododi1/INFINIX_SMART5_TWRP.git -b main device/infinix/x657b

      - name: Build recovery
        run: |
          cd twrp
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          lunch omni_x657b-eng
          make recoveryimage -j$(nproc --all)

      - name: Upload recovery image
        uses: actions/upload-artifact@v4
        with:
          name: twrp-x657b
          path: twrp/out/target/product/x657b/recovery.img
